# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_openssl_ssl_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TARGET_ARCH := $(TARGET_$(GYP_VAR_PREFIX)ARCH)
LOCAL_SDK_VERSION := 19
gyp_intermediate_dir := $(call local-intermediates-dir,,$(GYP_VAR_PREFIX))
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared,,,$(GYP_VAR_PREFIX))

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES :=

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/openssl/ssl/s2_meth.c \
	third_party/openssl/ssl/s2_srvr.c \
	third_party/openssl/ssl/s2_clnt.c \
	third_party/openssl/ssl/s2_lib.c \
	third_party/openssl/ssl/s2_enc.c \
	third_party/openssl/ssl/s2_pkt.c \
	third_party/openssl/ssl/s3_meth.c \
	third_party/openssl/ssl/s3_srvr.c \
	third_party/openssl/ssl/s3_clnt.c \
	third_party/openssl/ssl/s3_lib.c \
	third_party/openssl/ssl/s3_enc.c \
	third_party/openssl/ssl/s3_pkt.c \
	third_party/openssl/ssl/s3_both.c \
	third_party/openssl/ssl/s3_cbc.c \
	third_party/openssl/ssl/s23_meth.c \
	third_party/openssl/ssl/s23_srvr.c \
	third_party/openssl/ssl/s23_clnt.c \
	third_party/openssl/ssl/s23_lib.c \
	third_party/openssl/ssl/s23_pkt.c \
	third_party/openssl/ssl/t1_meth.c \
	third_party/openssl/ssl/t1_srvr.c \
	third_party/openssl/ssl/t1_clnt.c \
	third_party/openssl/ssl/t1_lib.c \
	third_party/openssl/ssl/t1_enc.c \
	third_party/openssl/ssl/t1_ext.c \
	third_party/openssl/ssl/d1_meth.c \
	third_party/openssl/ssl/d1_srvr.c \
	third_party/openssl/ssl/d1_clnt.c \
	third_party/openssl/ssl/d1_lib.c \
	third_party/openssl/ssl/d1_pkt.c \
	third_party/openssl/ssl/d1_both.c \
	third_party/openssl/ssl/d1_srtp.c \
	third_party/openssl/ssl/ssl_lib.c \
	third_party/openssl/ssl/ssl_err2.c \
	third_party/openssl/ssl/ssl_cert.c \
	third_party/openssl/ssl/ssl_sess.c \
	third_party/openssl/ssl/ssl_ciph.c \
	third_party/openssl/ssl/ssl_stat.c \
	third_party/openssl/ssl/ssl_rsa.c \
	third_party/openssl/ssl/ssl_asn1.c \
	third_party/openssl/ssl/ssl_txt.c \
	third_party/openssl/ssl/ssl_algs.c \
	third_party/openssl/ssl/ssl_conf.c \
	third_party/openssl/ssl/bio_ssl.c \
	third_party/openssl/ssl/ssl_err.c \
	third_party/openssl/ssl/kssl.c \
	third_party/openssl/ssl/t1_reneg.c \
	third_party/openssl/ssl/tls_srp.c \
	third_party/openssl/ssl/t1_trce.c \
	third_party/openssl/ssl/ssl_utst.c


# Flags passed to both C and C++ files.
MY_CFLAGS_Default :=

MY_DEFS_Default :=


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Default := \
	$(LOCAL_PATH)/third_party/openssl \
	$(LOCAL_PATH)/third_party/openssl/ssl \
	$(LOCAL_PATH)/third_party/openssl/crypto \
	$(LOCAL_PATH)/third_party/openssl/include


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Default :=


LOCAL_CFLAGS := $(MY_CFLAGS_$(GYP_CONFIGURATION)) $(MY_DEFS_$(GYP_CONFIGURATION))
LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES_$(GYP_CONFIGURATION))
LOCAL_CPPFLAGS := $(LOCAL_CPPFLAGS_$(GYP_CONFIGURATION))
LOCAL_ASFLAGS := $(LOCAL_CFLAGS)
### Rules for final target.
# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_openssl_ssl_gyp

# Alias gyp target name.
.PHONY: ssl
ssl: third_party_openssl_ssl_gyp

include $(BUILD_STATIC_LIBRARY)
